[phases.setup]
nixPkgs = ["rustc", "cargo", "openssl"]
nixpkgsArchive = "e37cc41c7a7c37b8fbe3fc322e087c49b58c7cb3"

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "cargo run --release"
