[phases.setup]
nixPkgs = ["openssl", "pkg-config"]

[phases.install]
cmds = [
  "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.82.0",
  "source $HOME/.cargo/env"
]

[phases.build]
cmds = ["source $HOME/.cargo/env && cargo build --release"]

[start]
cmd = "source $HOME/.cargo/env && cargo run --release"
